changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🚜 Maintenance
      labels:
        - maintenance
    - title: ❓ Uncategorized
      labels:
        - '*'
