changelog:
  exclude:
    labels:
      - article
  categories:
    - title: ⚠ Breaking Changes
      labels:
        - breaking
    - title: 🏕 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🚜 Maintenance
      labels:
        - maintenance
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: ❓ Uncategorized
      labels:
        - '*'
