changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - operations
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🚜 Operations
      labels:
        - operations
