min_version = "2026.4.8"

[tools]
actionlint = "1.7.12"
"aqua:suzuki-shunsuke/ghalint" = "1.5.5"
hadolint = "2.14.0"
"aqua:suzuki-shunsuke/pinact" = "3.9.0"
python = "3.14.4"
ruff = "0.15.9"
"aqua:astral-sh/ty" = "0.0.29"
uv = "0.11.6"
"aqua:zizmorcore/zizmor" = "1.23.1"
