min_version = "2026.4.8"

[settings]
install_before = "1d"

[tools]
node = "24.15.0"
python = "3.14.4"
"aqua:astral-sh/ruff" = "0.15.10"
"aqua:astral-sh/ty" = "0.0.30"
"aqua:astral-sh/uv" = "0.11.6"
"aqua:hadolint/hadolint" = "2.14.0"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:suzuki-shunsuke/ghalint" = "1.5.5"
"aqua:suzuki-shunsuke/pinact" = "3.9.0"
"aqua:zizmorcore/zizmor" = "1.24.1"
"npm:renovate" = "43.121.0"
