min_version = "2026.4.8"

[settings]
install_before = "1d"

[tools]
python = "3.14.4"

[tools."aqua:astral-sh/ruff"]
version = "0.15.12"
install_before = "0d"

[tools."aqua:astral-sh/ty"]
version = "0.0.32"
install_before = "0d"

[tools."aqua:astral-sh/uv"]
version = "0.11.8"
install_before = "0d"

[tools."pipx:uv-override-prune"]
version = "0.0.10"
install_before = "0d"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v1.3.0",
]
