min_version = "2026.4.8"

[settings]
install_before = "1d"

[tools]
python = "3.14.4"

[tools."aqua:astral-sh/uv"]
version = "0.11.8"
install_before = "0d"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v1.6.0",
]
