name: 'Auto label by title'
on:
  pull_request:
    types: [opened]
    branches: [ "main" ]

permissions: {}

jobs:
  label:
    permissions:
      pull-requests: write  # to add a label to the PR
    uses: iwamot/workflows/.github/workflows/auto-label.yml@ae85e64823f8d8316a33fa549c7a5ec13ab56795 # v8.6.1
