name: Auto approve

on: pull_request

permissions:
  contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'iwamot-renovate[bot]'
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: 'Auto approved automated PR'
            })
