name: 'Auto label by title'
on:
  pull_request:
    types: [opened]

permissions: {}

jobs:
  label:
    permissions:
      pull-requests: write  # to add a label to the PR
    uses: iwamot/workflows/.github/workflows/auto-label.yml@7e1e1b73633f829ea0ac1ca934aa4d085561d61a # v7.1.0
