name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: iwamot/workflows/.github/workflows/ci-with-coverage.yml@ddd824917bcf31b58113e4f8b14421436146bc17 # v0.8.0
