name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: iwamot/workflows/.github/workflows/ci-with-coverage.yml@4bd41065254022a2b4189e4d3faf19cc50d7a415 # v0.10.4
