name: DCO
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dco:
    permissions:
      pull-requests: read  # to read PR commits for DCO sign-off check
    uses: iwamot/workflows/.github/workflows/dco.yml@7e1e1b73633f829ea0ac1ca934aa4d085561d61a # v7.1.0
