name: DCO
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dco:
    permissions:
      pull-requests: read  # to read PR commits for DCO sign-off check
    uses: iwamot/workflows/.github/workflows/dco.yml@ae85e64823f8d8316a33fa549c7a5ec13ab56795 # v8.6.1
