name: DCO
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dco:
    permissions:
      pull-requests: read  # to read PR commits for DCO sign-off check
    uses: iwamot/workflows/.github/workflows/dco.yml@55c690f55783f59fcb2f2309d8c9feebb13bdc7d # v8.3.0
