name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write  # to comment review summary
    uses: iwamot/workflows/.github/workflows/dependency-review.yml@ae85e64823f8d8316a33fa549c7a5ec13ab56795 # v8.6.1
