name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write  # to comment review summary
    uses: iwamot/workflows/.github/workflows/dependency-review.yml@7e1e1b73633f829ea0ac1ca934aa4d085561d61a # v7.1.0
