name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot-auto-merge:
    permissions:
      contents: write       # to merge auto-merge PRs
      pull-requests: write  # to enable auto-merge
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@5a1f669fe305576b4e8cbbbfda639745027d3902 # v4.1.0
