name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot-auto-merge:
    permissions:
      contents: write       # to merge auto-merge PRs
      pull-requests: write  # to enable auto-merge
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@f4bb8660a94f68c9ac2228d5fad6b990adc922ff # v8.6.0
