name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot-auto-merge:
    permissions:
      contents: write       # to merge auto-merge PRs
      pull-requests: write  # to enable auto-merge
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@086f2d88815451da2cba7dc9e6e044d86c66743c # v8.2.0
