name: Oide

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/oide.yml

permissions: {}

jobs:
  pull:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/oide.yml@2999ae87b709bd1b1bb9ab110aa3055828848898 # v6.0.0
    with:
      # renovate: datasource=github-tags depName=iwamot/repo-template
      TEMPLATE_VERSION: v1.5.0
    secrets:
      OIDE_APP_CLIENT_ID: ${{ secrets.OIDE_APP_CLIENT_ID }}
      OIDE_APP_PRIVATE_KEY: ${{ secrets.OIDE_APP_PRIVATE_KEY }}
