name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ghcr.yml@4bd41065254022a2b4189e4d3faf19cc50d7a415 # v0.10.4
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
