name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ghcr.yml@afdf21101495a5ec5df69338e8f94ed6ee8cf32d # v3.4.0
    permissions:
      contents: read
      id-token: write   # to mint OIDC token for image signing
      packages: write   # to push to GHCR
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
