name: Publish Docker images

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    uses: iwamot/workflows/.github/workflows/publish-ghcr.yml@33f77c21f5d0189c92454aa0b8b2a809549bc598 # v1.0.0
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
