name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-ghcr.yml@3a106f414b2ee346211a9c9050a27e2f26336796 # v7.0.0
    permissions:
      contents: write  # to draft and publish the GitHub Release
      packages: write  # to push images to GHCR
      id-token: write  # to mint OIDC token for cosign signing
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
