name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-draft:
    name: release-draft
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write  # to create the draft GitHub Release
    steps:
      - uses: iwamot/actions/release-draft@35af46540ea16f3adb318c1a1739572b61f6fc53 # v0.8.0

  publish:
    needs: release-draft
    uses: iwamot/workflows/.github/workflows/publish-ghcr.yml@ae5512be479f765d6f3f89302516a6f5c0add845 # v4.1.3
    permissions:
      contents: read
      id-token: write   # to mint OIDC token for image signing
      packages: write   # to push to GHCR
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  release-publish:
    needs: publish
    name: release-publish
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write  # to flip the draft GitHub Release to published
    steps:
      - uses: iwamot/actions/release-publish@35af46540ea16f3adb318c1a1739572b61f6fc53 # v0.8.0
