name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
      id-token: write  # for Codecov OIDC upload
    uses: iwamot/workflows/.github/workflows/validate-with-coverage.yml@1d30033350f397a683dfdf04708d1a510969e9ed # v8.0.0
