name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
      id-token: write  # for Codecov OIDC upload
    uses: iwamot/workflows/.github/workflows/validate-with-coverage.yml@15e638a17daad208034700f2429ee13db2452ce4 # v4.2.0
