name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
      id-token: write  # for Codecov OIDC upload
    uses: iwamot/workflows/.github/workflows/validate-with-coverage.yml@afdf21101495a5ec5df69338e8f94ed6ee8cf32d # v3.4.0
